name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: nix build .#http-wasm-header-plugin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: result/bin/plugin.zip
