name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
#      extra_nix_config: |
#        access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}


      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-zip-artifact
          path: result/bin/plugin.zip